filter:
  excluded_paths:
  - 'vendor/*'
  - 'tests/*'
  paths:
  - 'src/*'

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

tools:

  external_code_coverage:
    timeout: 1200
    runs: 1